train: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/train/images
  scenes: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/train/scenes
  num_images: 100

val: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/val/images
  scenes: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/val/scenes
  num_images: 100

test: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/test/images
  scenes: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/test_task/test/scenes
  num_images: 100