# @package _group_/clevr_question_answering_train
scale: 2

train: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/train/images
  samples: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/train/question_answering/dataset.json
  max_samples: null

val: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/val/images
  samples: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/val/question_answering/dataset.json
  max_samples: null

test: 
  images: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/test/images
  samples: /home/tanmayg/Data/gpv/clevr_min_objects_1_max_objects_3/train_task/test/question_answering/dataset.json
  max_samples: null