# @package task_configs
image_dir: /home/tanmayg/Data/gpv/learning_phase_data/coco/images
image_size:
  H: 480
  W: 640
read_image: True
coco_feats: /home/tanmayg/Data/gpv/learning_phase_data/vg_det_feats
data_split: gpv_split

coco_captioning:
  image_dir: ${task_configs.image_dir}
  image_size: ${task_configs.image_size}
  read_image: ${task_configs.read_image}
  samples:
    train: /home/tanmayg/Data/gpv/learning_phase_data/coco_captions/${task_configs.data_split}/train.json
    val: /home/tanmayg/Data/gpv/learning_phase_data/coco_captions/${task_configs.data_split}/val.json
    test: /home/tanmayg/Data/gpv/learning_phase_data/coco_captions/${task_configs.data_split}/test.json
  max_samples:
    train: null
    val: null
    test: null
  feats: ${task_configs.coco_feats}
  data_split: ${task_configs.data_split}

coco_detection:
  image_dir: ${task_configs.image_dir}
  image_size: ${task_configs.image_size}
  read_image: ${task_configs.read_image}
  samples:
    train: /home/tanmayg/Data/gpv/learning_phase_data/coco_detection/${task_configs.data_split}/train.json
    val: /home/tanmayg/Data/gpv/learning_phase_data/coco_detection/${task_configs.data_split}/val.json
    test: /home/tanmayg/Data/gpv/learning_phase_data/coco_detection/${task_configs.data_split}/test.json
  max_samples:
    train: null
    val: null
    test: null

coco_classification:
  image_dir: ${task_configs.image_dir}
  image_size: ${task_configs.image_size}
  read_image: ${task_configs.read_image}
  samples:
    train: /home/tanmayg/Data/gpv/learning_phase_data/coco_classification/${task_configs.data_split}/train.json
    val: /home/tanmayg/Data/gpv/learning_phase_data/coco_classification/${task_configs.data_split}/val.json
    test: /home/tanmayg/Data/gpv/learning_phase_data/coco_classification/${task_configs.data_split}/test.json
  max_samples:
    train: null
    val: null
    test: null

coco_vqa:
  image_dir: ${task_configs.image_dir}
  image_size: ${task_configs.image_size}
  read_image: ${task_configs.read_image}
  samples:
    train: /home/tanmayg/Data/gpv/learning_phase_data/vqa/${task_configs.data_split}/train.json
    val: /home/tanmayg/Data/gpv/learning_phase_data/vqa/${task_configs.data_split}/val.json
    test: /home/tanmayg/Data/gpv/learning_phase_data/vqa/${task_configs.data_split}/test.json
    testdev: /home/tanmayg/Data/gpv/learning_phase_data/vqa/${task_configs.data_split}/testdev.json
  max_samples:
    train: null
    val: null
    test: null
    testdev: null
  feats: ${task_configs.coco_feats}
  data_split: ${task_configs.data_split}