learning_datasets:
  CocoCaptioning:
    task_config: coco_captioning
    name: coco_cap
  CocoDetection:
    task_config: coco_detection
    name: coco_det
  CocoClassification:
    task_config: coco_classification
    name: coco_cls
  CocoVqa:
    task_config: coco_vqa
    name: coco_vqa