exp_name: detr_num_queries_${model.detr.num_queries}_lr_${training.lr}
output_dir: /home/tanmayg/Data/gpv/exp
exp_dir: ${output_dir}/${exp_name}
tb_dir: ${exp_dir}/tb_logs
ckpt_dir: ${exp_dir}/ckpts

hydra:
  run:
    dir: ${output_dir}/${exp_name}

defaults:
  - task: clevr_detection_train_task

model:
  detr:
    num_queries: 50
    num_classes: 1
    hidden_dim: 256
    nheads: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    backbone: resnet50
    lr_backbone: 1e-5
    position_embedding: sine
    masks: False
    dilation: False
    dropout: 0.1
    dim_feedforward: 2048
    pre_norm: True
    aux_loss: True
    frozenbatchnorm: False

training:
  num_epochs: 300
  batch_size: 16
  vis_step: 500
  log_step: 100
  ckpt_step: 500
  lr: 1e-4
  weight_decay: 1e-4
  lr_drop: 150
  cost_wts:
    ce: 1
    bbox: 5
    giou: 2
  loss_wts:
    ce: 1
    bbox: 5
    giou: 2
  eos_coef: 0.1
  clip_max_norm: 0.1
  num_vis_samples: 5

eval:
  step: 1000
  batch_size: ${training.batch_size}
  iou_thresh: 0.5
  