exp_name: default
output_dir: /home/tanmayg/Data/gpv/coco_exp
exp_dir: ${output_dir}/${exp_name}
results_dir: ${output_dir}/${exp_name}/eval
subset: test
tasks:
  - RefCocop
  - CocoVqa
  - CocoCaptioning
  - CocoDetection
  - CocoClassification

hydra:
  run:
    dir: ${output_dir}/${exp_name}/eval